# Generated by Django 3.2 on 2021-04-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('magic_number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trailer_link', models.URLField(max_length=250)),
            ],
        ),
    ]
