# Generated by Django 3.2 on 2021-04-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='magic_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='trailer_link',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
