# Generated by Django 3.2 on 2021-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210423_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='magic_number',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='trailer_link',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
    ]
