# Generated by Django 3.2 on 2021-04-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210423_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='magic_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
