# Generated by Django 3.2 on 2021-04-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210424_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weblink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamefaqs', models.URLField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='weblinks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.weblink'),
        ),
    ]
