# Generated by Django 3.2 on 2021-04-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210424_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='weblinks',
        ),
        migrations.AddField(
            model_name='game',
            name='gamefaqs_link',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
        migrations.DeleteModel(
            name='Weblink',
        ),
    ]
