# Generated by Django 3.2 on 2021-04-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210424_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='howlongtobeat_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='HowLongToBeat Link'),
        ),
        migrations.AddField(
            model_name='game',
            name='main_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='Main Website'),
        ),
        migrations.AddField(
            model_name='game',
            name='mobygames_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='MobyGames Link'),
        ),
        migrations.AddField(
            model_name='game',
            name='pcgamingwiki_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='PCGamingWiki Link'),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='Steam Link'),
        ),
        migrations.AddField(
            model_name='game',
            name='vndb_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='VNDB Link'),
        ),
        migrations.AddField(
            model_name='game',
            name='wikipedia_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='Wikipedia'),
        ),
        migrations.AddField(
            model_name='game',
            name='winehq_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='WineHQ Link'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamefaqs_link',
            field=models.URLField(blank=True, default='', max_length=250, verbose_name='GameFAQs Link'),
        ),
    ]
