# Generated by Django 3.2 on 2021-04-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20210424_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
