# Generated by Django 3.2 on 2021-04-24 02:18

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20210424_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screen1',
            field=models.ImageField(null=True, upload_to=games.models.random_screen_filename),
        ),
        migrations.AddField(
            model_name='game',
            name='screen2',
            field=models.ImageField(null=True, upload_to=games.models.random_screen_filename),
        ),
        migrations.AddField(
            model_name='game',
            name='screen3',
            field=models.ImageField(null=True, upload_to=games.models.random_screen_filename),
        ),
        migrations.AddField(
            model_name='game',
            name='screen4',
            field=models.ImageField(null=True, upload_to=games.models.random_screen_filename),
        ),
    ]
