# Generated by Django 3.2 on 2021-04-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20210424_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name']},
        ),
    ]
