# Generated by Django 3.2 on 2021-04-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20210427_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edits_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games_added',
            field=models.IntegerField(default=0),
        ),
    ]
