# Generated by Django 3.2 on 2021-04-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20210427_2205'),
        ('games', '0019_auto_20210430_0002'),
    ]

    operations = [
    ]
