# Generated by Django 3.2.4 on 2021-06-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_manualusergamelistentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualusergamelistentry',
            name='year',
        ),
    ]
