# Generated by Django 3.2.4 on 2021-06-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_remove_manualusergamelistentry_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualusergamelistentry',
            name='times_replayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergamelistentry',
            name='times_replayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manualusergamelistentry',
            name='status',
            field=models.CharField(choices=[('PLAY', 'Playing'), ('CMPL', 'Completed'), ('DROP', 'Dropped'), ('HOLD', 'Paused'), ('PLAN', 'Plan to Play'), ('IMPT', 'Imported')], default='PLAN', max_length=4),
        ),
        migrations.AlterField(
            model_name='usergamelistentry',
            name='status',
            field=models.CharField(choices=[('PLAY', 'Playing'), ('CMPL', 'Completed'), ('DROP', 'Dropped'), ('HOLD', 'Paused'), ('PLAN', 'Plan to Play'), ('IMPT', 'Imported')], default='PLAN', max_length=4),
        ),
    ]
